apiVersion: v1
kind: Secret
metadata:
  name: tsn-secrets
  namespace: tsn
type: Opaque
# Values are base64 encoded
# To encode: echo -n "your_value" | base64
stringData:
  MONGO_URI:                 "mongodb://tsn_admin:tsn_secret_2024@mongo-service:27017/tsn_cameroon?authSource=admin"
  MONGO_ROOT_USERNAME:       "tsn_admin"
  MONGO_ROOT_PASSWORD:       "tsn_secret_2024"
  REDIS_PASSWORD:            "tsn_redis_2024"
  JWT_SECRET:                "tsn_jwt_secret_cameroon_2024_change_in_production"
  AFRICAS_TALKING_KEY:       "YOUR_AFRICAS_TALKING_KEY"
  AFRICAS_TALKING_USERNAME:  "YOUR_AFRICAS_TALKING_USERNAME"
  MTN_API_KEY:               "YOUR_MTN_API_KEY"
  MTN_API_SECRET:            "YOUR_MTN_API_SECRET"
  ORANGE_API_KEY:            "YOUR_ORANGE_API_KEY"
  GOOGLE_MAPS_API_KEY:       "YOUR_GOOGLE_MAPS_API_KEY"
